admin_post:
    path:     /index/{page}
    defaults: { _controller: "BlogAdminBundle:Post:index", page: 1 }

admin_post_show:
    path:     /{id}/show
    defaults: { _controller: "BlogAdminBundle:Post:show" }

admin_post_new:
    path:     /new
    defaults: { _controller: "BlogAdminBundle:Post:new" }

admin_post_create:
    path:     /create
    defaults: { _controller: "BlogAdminBundle:Post:create" }
    methods:  POST

admin_post_edit:
    path:     /{id}/edit
    defaults: { _controller: "BlogAdminBundle:Post:edit" }

admin_post_update:
    path:     /{id}/update
    defaults: { _controller: "BlogAdminBundle:Post:update" }
    methods:  [POST, PUT]

admin_post_delete:
    path:     /{id}/delete
    defaults: { _controller: "BlogAdminBundle:Post:delete" }
    methods:  [POST, DELETE]
    
admin_post_remove:
    path:     /{id}/remove
    defaults: { _controller: "BlogAdminBundle:Post:remove" }
    
admin_post_showcomment:
    path:     /{id}/showcomment
    defaults: { _controller: "BlogAdminBundle:Post:showComment" }
    
admin_post_enablecomment:
    path:     /{id}/enablecomment
    defaults: { _controller: "BlogAdminBundle:Post:enableComment" }
    
admin_post_remove-image:
    path:     /{id}/{img}/remove-image
    defaults: { _controller: "BlogAdminBundle:Post:removeImage" }
    
admin_post_up-image:
    path:     /{id}/{img}/up-image
    defaults: { _controller: "BlogAdminBundle:Post:upImage" }
    
admin_post_down-image:
    path:     /{id}/{img}/down-image
    defaults: { _controller: "BlogAdminBundle:Post:downImage" }
    
admin_post_sort-image:
    path:     /{id}/sort-image
    defaults: { _controller: "BlogAdminBundle:Post:sortImage" }
    #methods:  [POST]
