# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        #BlogBundle\Entity\User: plaintext #Bez szyfrowania hasła
        BlogBundle\Entity\User: bcrypt
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [in_memory, database_users]
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        database_users:
            entity: { class: BlogBundle\Entity\User, property: username }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        backend_secured_area:
            pattern:    ^/dashboard
            form_login:
                #login_path: /dashboard/backend_login
                #check_path: /dashboard/backend_login_check
                login_path: blog_backend_login
                check_path: blog_backend_login_check
            logout:
                #path:   /dashboard/backend_logout
                #target: /dashboard
                path:   blog_backend_logout
                target: blog_admin_homepage
            anonymous: ~

        frontend_secured_area:
            pattern:    ^/
            form_login:
                #login_path: /frontend_login
                #check_path: /frontend_login_check
                login_path: blog_frontend_login
                check_path: blog_frontend_login_check
            logout:
                #path:   /frontend_logout
                #target: /
                path:   blog_frontend_logout
                target: blog_homepage
                #target: blog_homepage #przekierowanie do strony głównej po wylogowaniu
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/dashboard/backend_login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dashboard, roles: ROLE_ADMIN }
        - { path: ^/frontend_login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/archive, roles: ROLE_USER }
        #- { path: ^/blog, roles: ROLE_USER }
