<?php

namespace BlogAdminBundle\Repository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMaxRank($post_id = null)
    {
        $qb = $this->createQueryBuilder('i');

        if($post_id)
        {
            $qb->select('MAX(i.rank) as rank')
              ->where('i.post = :post_id')
              ->setParameter('post_id', $post_id);
        }

        $query = $qb->getQuery();

        return $query->getSingleResult();
    }
    
    public function updateRank($post_id = null)
    {
        $qb = $this->createQueryBuilder('i');

        if($post_id)
        {
            $qb->where('i.post = :post_id')
              ->setParameter('post_id', $post_id)
              ->orderBy('i.rank', 'ASC');
        }
        
        $images = $qb->getQuery();
        
        return $images->getResult();
    }
}
