# src/BlogBundle/Resources/config/doctrine/Tag.orm.yml
BlogBundle\Entity\Tag:
  type: entity
  repositoryClass: BlogBundle\Repository\TagRepository
  table: tag
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 50
      unique: true
    slug:
      type: string
      length: 50
      unique: true
    description:
      type: string
      length: 255
      nullable: true
  manyToMany:
    posts:
      targetEntity: Post
      mappedBy: tags
      #cascade: [ persist ]
  lifecycleCallbacks:
    prePersist: [ setSlugValue ]